### ISSUE TITLE
Empty response of collection throws error

### ISSUE THREAD

**Issue by goldsky** [SitePen/dstore#103]
I found that if the collection gets empty response, it throws error.
*Firebug:*
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
var results = collection.parse(response);
Request.js (line 135)
```

So, I modified it for a test, and this update kind of working:
```javascript

				data: response.then(function (response) {
//					var results = collection.parse(response);
                    try {
                        var results = collection.parse(response);
                    } catch (ex) {
                        return new Array();
                    }
```

**Comment by kfranqueiro** [comment]
Shouldn't a response with no items technically still be `[]`?  That's what the existing code is assuming - that it gets valid JSON in any event.

If we wanted to support a truly empty response, I imagine a more efficient way sans try/catch would be `var results = response ? collection.parse(response) : [];`

**Comment by goldsky** [comment]
That can do

**Comment by twelveeighty** [comment]
I just ran into this problem as well, with a twist. I have a Rest server returning "204 No Content" with an empty response for certain Put operations. JsonRest did not have a problem with this, but dstore/Rest throws an error.

Does REST (the convention) assume that a put operation always returns the changed content? Or is 204 No Content with an empty content still a valid response?

I noticed that Rest.delete() does check for empty content, but Rest.put() punches the content directly into JSON.parse().

**Comment by kriszyp** [comment]
Fixed with https://github.com/SitePen/dstore/commit/a5d7957ff6077d2608df6d45736635feb7ff6093 (ugh, was one number off on the commit comment).

**Comment by kriszyp** [comment]
Also, just FYI, this commit only fixes the issue with empty content on a put(). I don't think it is advisable to return a 204 with no content for a GET request expecting a JSON array.

**Comment by twelveeighty** [comment]
I think that's a perfectly valid assumption: GET is expected to return a response, or empty array [ ] if no results are found. PUT, POST and DELETE could return empty content, which (I believe) the server also should accompany with a 204 code.
