### ISSUE TITLE
nested queries fail

### ISSUE THREAD

**Issue by neonstalwart** [SitePen/dstore#119]
see http://jsfiddle.net/neonstalwart/635o1nmp/

i believe the issue is because https://github.com/SitePen/dstore/blob/267c620932d49ba5ff82ee2dfe287597066ef2f4/SimpleQuery.js#L74 is too tricky.  

`querier` gets assigned to from within `getQuerier` and `getQuerier` recurses on itself so that variable gets written to in some weird ways that will cause nested queries to be applied with their parent query (i think) - i.e. a recursive call to `getQuerier` will leave `querier` set and affect the call that recursed into `getQuerier` when it gets down to the `switch` statement.

**Comment by kriszyp** [comment]
Committed in https://github.com/SitePen/dstore/commit/f5e2f6898ff28c81aa373f2c2a4df84488d2bc05

**Comment by kriszyp** [comment]
Thank you!

**Comment by neonstalwart** [comment]
i also had a test at #120 to prevent regressions if you wanted to include it.
