### ISSUE TITLE
How to assign a Model to an IndexedDB?

### ISSUE THREAD

**Issue by marakante** [SitePen/dstore#126]
How can I use a Model (dmodel/Model) in an IndexedDB (dstore/db/IndexedDB, dstore version 1.1)?

Using a Memory store it works fine. But I don't know "where" or "how" to put the Model in an IndexedDB.

with:
```javascript
    var myConfig = {...};
    var MyModel = declare(Model, { schema: {...} });
    var db = new IndexedDB({dbConfig: myConfig, storeName: 'store1', Model: MyModel})
```
then In Firebug I can see the *constructor* Model is assigned to db, but data retrieved from the store are not decorated anyway.

Thanks,
Martin

(I tried this on the dojo-mailing list already. But I can't see my posting there)

**Comment by kfranqueiro** [comment]
FYI, your ML post did come through: http://mail.dojotoolkit.org/pipermail/dojo-interest/2015-May/084372.html
