### ISSUE TITLE
Csv tests fail on Windows

### ISSUE THREAD

**Issue by kfranqueiro** [SitePen/dstore#132]
I noticed today that the Csv unit tests seem to fail.  This happens to me on master, 1.1.0, and 1.0.x.

I find it hard to believe we would have overlooked these failing all this time, and I know the Csv code and tests were based on code originally from my own dojo-smore and those work.  So I'm not sure when this went wrong, or whether the bug is in the implementation or the tests.

**Comment by kfranqueiro** [comment]
I can't reproduce this on my Mac...  I am suddenly suspicious that git's autocrlf setting could have something to do with this, which would be pretty annoying.

**Comment by kriszyp** [comment]
Yeah, I've noticed this as well, and assumed I was having local crlf issues.
