### ISSUE TITLE
Update package.json to correctly reflect the license

### ISSUE THREAD

**Issue by dylans** [SitePen/dstore#152]
package.json shows AFL and BSD, but LICENSE lists just the BSD. npm shows AFL as it takes the first package from the list.

We should remove AFL from the list in package.json, or if we have a reason to keep it, we should at least list it second in the license list.

**Comment by kitsonk** [comment]
I suspect it was just someone doing a copy paste originally for the `package.json`.

**Comment by kitsonk** [comment]
Fixed via #155
