### ISSUE TITLE
Questionable PutSync performance

### ISSUE THREAD

**Issue by fedoranimus** [SitePen/dstore#183]
What are expectations for performance when adding new items to a store via `PutSync()` as opposed to updating existing items in a store via `PutSync()`?

I've noticed a significant difference between the two, demonstrated by the following trivial code:

``` javascript
let testStore = new MemoryStore<any>({});
console.time("addingData");
for (let i = 0; i < 100000; i++) {
    testStore.putSync({id: i, value: i});
}
console.timeEnd("addingData");
console.time("puttingData");
for (let i = 0; i < 100000; i++) {
     testStore.putSync({ id: i, value: i });
}
console.timeEnd("puttingData");
```

The following times are returned:

```
addingData: 430.055ms (~.5s)
puttingData: 257644.077ms (~4.3min)
```

Is such a significant difference expected?

**Comment by dylans** [comment]
That certainly does not look ideal at all. I'm wondering if https://github.com/SitePen/dstore/commit/196cf08926bf04d3f457b3e851913521ceb05498 is at all related, or if the type of fix made there needs to be applied elsewhere...

**Comment by rgillan** [comment]
I know it's a number of years but has anyone looked at this?  We're seeing similar update performance with our production application (dStore/dGrid) where there's around a ~2-3s update per record on a largish Memory store (~30k records) and it's causing all sorts of grief (initial load is fine).  Thanks as always, Rob

**Comment by rgillan** [comment]
So with further testing, it's not the dStore putSync in our case.  It's somewhere downstream in the chain (trackable memory store into dGrid).  Just the putSync process is averaging 0.02-0.03mS per overwrite/update).  I'll update our findings here in case it's helpful.

**Comment by rgillan** [comment]
just to update with our findings.  Turns out it was the individual events triggering the trackable capability of the dGrid.  Our data is highly fluid, with some cases sustaining 100-150 changes per second.  The dStore is happily updating; we've just set a more manual update of the dGrid collection.
