### ISSUE TITLE
Event handler errors are silently swallowed

### ISSUE THREAD

**Issue by kriszyp** [SitePen/dstore#187]
The `return` statement inside the `finally` block in the `emit` causes thrown errors to be caught and silently ignored:
https://github.com/SitePen/dstore/blob/1.x/Store.js#L141

Ideally it would be nice if we were not catching errors at all, to avoid interrupting the error stack, but at the very least if we are going to be catching errors, we should at least report them with some console output so they don't just silently disappear.

**Comment by xmedeko** [comment]
Very annoying bug, it's very hard to hunt bugs - swallowed errors.
