### ISSUE TITLE
Trackable fires events on all collections, even if element is not in it.

### ISSUE THREAD

**Issue by gtk-aschmidt** [SitePen/dstore#188]
Let's say I have one store, and two collections defined on that store, each viewing a different subset of information, and I'm tracking both collections:

```
// Only the Driver's comments
this.driverCollection=this.commentStore.filter({
    vehicleid:this.vehicleid,
    inspectitemid:this.inspectitemid,
    commenter:'Driver'
}).sort([{property:'commenttime',descending:true}]).track();

// Only the Mechanic's comments
this.mechanicCollection=this.commentStore.filter({
    vehicleid:this.vehicleid,
    inspectitemid:this.inspectitemid,
    commenter:'Mechanic'
}).sort([{property:'commenttime',descending:true}]).track();
```

If I add a listener to each collection and add a record, both listeners are notified.

```
this.mechanicCollection.on('delete,add,update',function(evt){
    // I will get events when the commenter is 'Driver'
});
```

**Comment by denov** [comment]
i'm also seeing this behavior 1.1.2.  one would expect the track to only happen on the collection and not the store.

**Comment by edhager** [comment]
@gtk-aschmidt and @denov,

We landed a fix in the master branch.  the `Store#on` method now supports a third, optional parameter.  Take a look at the comments in #222 to see the limitations of registering an "update" event listener.
