### ISSUE TITLE
LocalDB gets confused if multiple queries done at same time.

### ISSUE THREAD

**Issue by wildcatcs** [SitePen/dstore#195]
When using LocalDB backed by indexedDB the calls are truly async.  If two or more queries are made on the store at the same time the result set for both queries are incorrect.  

For example if there is a table with an index on type and the type can be either 'car' or 'truck' 

if you do the two queries below at the same time
store.filter({type:'car'}).forEach(.....) 
store.filter({type:'truck'}).forEach(.....) 

The first or second query will container results with items that should be in the other result set.

**Comment by lzhoucs** [comment]
I couldn't reproduce this issue. I put up [a simple example on plunker](http://plnkr.co/edit/oH9RpghDK1V5hdL9bZya?p=preview) which shows that the LocalDB is working as expected. Behaviors may vary by browser, so please let us know if there are any issues.

**Comment by wildcatcs** [comment]
This was very repeatable but non-deterministic on chrome using versions 42 on.  There were large numbers of items in the indexedDB tables (1000+).

**Comment by bitpshr** [comment]
A test case that demonstrates this issue can be found here: https://jsfiddle.net/jubn5g5y/1/.

Note that there's one lone (and duplicated) `odd: ... ` log before the `even: ...` logs start. I can't figure out why that single odd log statement prints before the even log statements, or why it's duplicated when the rest of the odd log statements start.

**Comment by pottedmeat** [comment]
This fix addresses the internal storage of the `all` object but will still result in `forEach` being called twice. Because this is called after a successful operation, we should advance our position within the cursor the next time it is opened and leave the value of `all` untouched.
