### ISSUE TITLE
dgrid/Rest does not parse arrays of JSON in get(1)

### ISSUE THREAD

**Issue by gardiol** [SitePen/dstore#217]
Maybe this is not an error, but since i spent one full day hunting this down, associated with the sheer lack of documentation and tutorials on the subject...

If you have a dstore/Rest collection and edit an item, the dstore will issue a GET before issuing the PUT/POST. Well, if the GET return an array of one json elements, dstore/Rest is confused, cannot parse it and will issue a POST instead of a PUT even if the proper "id" field is present. The issue seems to be inside 
`getIdentity: function (object) {
			return object.get ? object.get(this.idProperty) : object[this.idProperty];
		},`
Because object[this.idProperty] is not set, the idProperty field is set one level lower.

The "incorrect" JSON is something like: [{"id": "4", "value": "test"}]
While the "correct" JSON would be: {"id": "4", "value": "test"}

If your GET backend report the first, dstore/Rest will to a POST after the GET. With the latter, it will correctly perform a PUT after the GET.

To be clear: the "incorrect" JSON above is some perfectly correct JSON, and it shuld be correctly interpreted by dstore/Rest as one element...

**Comment by msssk** [comment]
`Store#get` accepts a unique identifier and returns a single object. To maintain API consistency, and to follow common REST paradigms, a service that receives a request for an item by id should return an object representing that item. There is also a preservation of symmetry: POST/PUT sends a single object in the body, the corresponding GET should return a single object, not an array containing the object.

While the JSON array is valid, in the context of a RESTful API it is atypical and in the context of dstore it is invalid.
