### ISSUE TITLE
IndexedDB fails to create index if you use a not default 'idProperty'

### ISSUE THREAD

**Issue by denov** [SitePen/dstore#219]
There needs to be a check for non index objects in the store config.  Adding index !== 'idProperty' the check below seems to fix it.  I'm not sure if the check for autoIncrement should be there as it's normally a property of the index object of storeConfig.

```
for (var index in storeConfig) {
	if (!idbStore.indexNames.contains(index) && index !== 'autoIncrement' 
                  && index !== 'idProperty'  && storeConfig[index].indexed !== false) {
		idbStore.createIndex(index, index, storeConfig[index]);
	}
}

```

**Comment by msssk** [comment]
I think this is fixed in #198.
