### ISSUE TITLE
QueryResults.forEach callback parameters not as expected

### ISSUE THREAD

**Issue by markaedwards** [SitePen/dstore#39]
Hi
Just a little thing, just started using the latest release which has introduced QueryResults.  The forEach function calls the provided callback with the parameters -
data[i], data
whereas the normally expected signature for a forEach callback would have the index as the second parameter i.e. -
data[i], i, data

Loving the whole dstore thing, nice work!

Regards

Mark

**Comment by csnover** [comment]
The commit in the previous comment fixes only `Store#forEach`, not `QueryResults#forEach`. The latter API is still broken until 9afdf9e3047f74f5b3882c0b7e6d06e305c3e2c0 and there hasn’t been a new release since then with the fix.
