### ISSUE TITLE
Plans for CDN Package?

### ISSUE THREAD

**Issue by gisdev-km** [SitePen/dstore#86]
Will there be plans to put a CDN hosted package for dstore similar to dgrid via rawgit?

**Comment by kfranqueiro** [comment]
It's already automatically available on rawgit - that's how rawgit works.  Just configure a `dstore` package to point to `//cdn.rawgit.com/SitePen/dstore/v1.0.0`

**Comment by gisdev-km** [comment]
Ah, I was trying v0.1.0 and having 404 errors. 

Thx.

**Comment by kriszyp** [comment]
I think this has been fixed.

**Comment by kfranqueiro** [comment]
Actually it would probably be good to update the website's zip link again - it's pointing to 1.0.0 but 1.0.1 is a thing now :)

**Comment by kriszyp** [comment]
I can see that this is something I definitely don't want to maintain...

**Comment by kriszyp** [comment]
I wonder if we could just use the URL https://github.com/SitePen/dstore/releases/latest

**Comment by kfranqueiro** [comment]
That seems like it could be a good idea in this case.
