### ISSUE TITLE
Options for store's sort and Null values ?

### ISSUE THREAD

**Issue by Jens-dojo** [SitePen/dstore#88]
Hello,

I have a lot of Null values in my stores.
Sometimes when the field is a String type , sometimes when the field is a numeric value.

The store's sort() method is

sort(property, [descending])

I have currently no chance to influence how Null values are sorted:
- at the beginning of the collection
- at the end
- always at the end/beginning - independent of the "descending" parameter.

What do you think about the idea to add an additional parameter to sort() to handle that?

It would not be too much coding and it wouldn't break any existing code/API.

Best wishes
Jens

**Comment by kriszyp** [comment]
I think the biggest effort here is implementing this for SQL and IndexedDB. For IndexedDB, I think we will just give up, and use in-memory sorting if nullPosition is specified. For SQL, I will probably need to brush up on my ORDER BY syntax to accomplish this. For now this is in a branch.

**Comment by Jens-dojo** [comment]
Dear Kris,

thank you for your code changes !
Very much appreciated !!!

Jens

**Comment by kfranqueiro** [comment]
FYI, I just landed #133, which while not as flexible as what was discussed here, at least makes null and undefined values sort predictably.

**Comment by kitsonk** [comment]
Looks like this issue was addressed.  Closing.
