### ISSUE TITLE
Searching in sub-array

### ISSUE THREAD

**Issue by mercmobily** [SitePen/dstore#91]
Hi,

If after a `fetch` I end up with something like this:

    [
      { 
        name: 'Tony',
        surname: 'Mobily',
        _children: {
          emails: [
            { address: 'one@example.com' },
            { address: 'two@example.com' },
            { address: 'three@example.com' },
          ]
        }
      },

      { 
        name: 'Chiara',
        surname: 'Mobily',
        _children: {
          emails: [
            { address: 'three@example.com' },
            { address: 'four@example.com' },
            { address: 'five@example.com' },
          ]
        }
      }
    ]
What is the easiest way for me to tweak dstore so that I can query like this:

    store.filter(  {'_children.emails.address': 'three@example.com' } ).fetch()

And get those two records returned?
Simplifications: there can only be ONE level down (so, no searching in `_children` under another `_children`. Also, the query could be simplified to `emails.address` (if there is a `.`, then `_children` is implied).

I am asking because this is how server querying works at the moment (well, close: the server will actually accept, as a filter field, `_emails.address`) and I want to find the "nirvana" in store creation, where _client-side stores follow the exact same filtering rules as the server_, so that I never ever have to worry about positioning or "simulating what the server does" _ever_ again.

I am looking at the code, and am realising that this would be a pretty painful change, since it will actually involve every single operator (which might get applied to a simple element, or to "any one element in an array"). I was keen on extending Memory.js/SimpleQuery and be merry. But now I noticed that you are adding LocalStorage (exciting!) and the `in` operator now can look into the results of another store... so things are getting tricky, and am starting to think that I would end up with a bit of a monster.

The reason why I need this is pretty exciting: that's how my server returns values (I return the first level of joins, which reduces a _lot_ the number of calls to the server); also, anything in the 1st level of join is searchable at db-level (which, in my case, when it's MongoDb, data is pre-cached which means that I can make _one_ select request, and return the record and _all_ direct children). If I manage to pull this "nested querying" off, it will mean that I will have 100% equivalent querying on the client and on the server, which has the obvious consequence that placement of items when using positioning will always be consistent.

Help?

Thanks as ever,

Merc.

**Comment by kriszyp** [comment]
Would it be sufficient to add support for nested properties (dot.delimited) in:
https://github.com/SitePen/dstore/blob/master/SimpleQuery.js#L74
And then you could do a filter with:
store.filter(new Filter().contains('_children.emails', new Filter().eq('address', 'three@example.com')))
I am not sure if that would work, but is that what you are aiming for?

**Comment by mercmobily** [comment]
When did the "contains" filter pop up...?!?
Yes, looking at the code, I think that would actually work. I mean, if comparator had dot-notation, you could make queries really as deep as you like. But, would you say that we ought to skip the `object.get()` altogether if there is dot notation?
(Wow... if this is so easy to fix, it would be _huge_! The power of an amazing architecture at work...

**Comment by kriszyp** [comment]
You think we should pass the dot-delimited string into `object.get(path)`? I was thinking of repeatedly calling the expression `object.get ? object.get(firstArg) : object[firstArg]` for each segment in the path.

**Comment by mercmobily** [comment]
Actually yes you are absolutely right. Plus this would be something that
would actually make dstore more powerful ad a whole!

**Comment by mercmobily** [comment]
Hey Kris, one question... Is this something you consider useful enough to
be worthy of dstore? Or something you expect me to keep in my own fork?

If you do think it's something worth of dstore, is it something you already
wrote/about to write? Or do you think I should have a go? (I am asking
because I have the feeling you might tear my code to bits when you see it
:) ).

Let me know... Ta!

**Comment by kriszyp** [comment]
I was thinking about working on it tomorrow. I think the challenge here is making sure we could apply this with the IndexedDB and SQL stores. If you want to crack at it you are welcome as well (or have ideas).

**Comment by mercmobily** [comment]
Hi,

I was thinking about working on it tomorrow. I think the challenge here is
> making sure we could apply this with the IndexedDB and SQL stores. If you
> want to crack at it you are welcome as well (or have ideas).
>

When did WebSql and IndexedDB popped out?!?
OK I obviously missed out on the latest development of dstore. I had no
idea you had focused on local stores so much. Dstore is becoming a huge and
hugely elegant data juggler!

I thought I could have a crack at it till I saw the code for WebSQL. I
don't know the codebase, and it would take me a looooong time to work the
basic things out... (Having said that, I ought to get to know the codebase
better, since 1) It's not that big 2) It's good for me to know it).

It would be amazing for me to see how you get this to work.

Merc.

**Comment by dylans** [comment]
> When did WebSql and IndexedDB popped out?!?

They landed in dojox/store for Dojo 1.10, and they've been in a branch for dstore for quite a while (pre 1.0), and landed in master about a month ago.

**Comment by mercmobily** [comment]
I need to stop writing emails while entertaining my son... " When did
WebSql and IndexedDB pop** out?!?"

Anyhow, I had missed them completely. Looking at the code, and the
implementation of `contains`, I take my hat off!

**Comment by kitsonk** [comment]
Looks like this is resolved... so closing.
