### ISSUE TITLE
dstore is registered in bower but without a bower.json it is not able to install its dependencies.

### ISSUE THREAD

**Issue by clmath** [SitePen/dstore#94]
When you run `bower install dstore`, dstore is installed without dojo so it is not working out of the box.
It would be nice to add a `bower.json` file with the dojo dependency so `bower install store` result in a usable installation.

See also: https://github.com/ibm-js/generator-deliteful-app/pull/7

**Comment by cjolif** [comment]
:+1:

**Comment by cjolif** [comment]
thanks!
